### ISSUE TITLE
Prefedined object notation for Reference

### ISSUE THREAD

**Issue by roccx** [JamitLabs/SimpleAPISpec#2]
We specify that every response body has to include the properties `typeName` and `identifier` as metadata.

Would it be an Idea to move metadata to a child object?
This would be a nice advantage for client implementations to have a reusable `Reference` or `Meta` type.

**Comment by Dschee** [comment]
I don't understand what your exact suggestion is here. Do you want to nest the fields into a subhash? Anything else I might think of should not be part of this spec, instead a library can define their reusable `Reference` or `Meta` type themselves if they want to – but in any case it's an implementation detail for me. Please explain further what you exact suggestion is...

**Comment by roccx** [comment]
The `typeName` and `identifier` properties are not really a part of the Model itself but more a meta description of the Model.

As the readme describes everybody would at least require `typeName` and `identifier` to be a valid response. So if everything has to have it, why aren't we defining as a sub-hash?

**Comment by Dschee** [comment]
In the [initial commit](https://github.com/JamitLabs/SimpleAPISpec/tree/d865208775884e699adba345e67cabd42619a3cc) of this API spec we actually had it the other way around: The properties were part of a subhash called `data`. This makes in my opinion more sense than having a subhash for the stuff that's always there. But the feedback from Thomas was that it would make things harder this way and having them at the same layer would be better. I personally still like the other approach better, but I took his feedback seriously.
